### ISSUE TITLE
ctrl-y as yank on macOS is not supported

### ISSUE THREAD

**Issue by nox** [Microsoft/vscode-sublime-keybindings#35]
This is useful in conjunction with ctrl-k.

**Comment by waderyan** [comment]
Thanks for opening this issue. Because yank is not supported in VS code yet, we need to add it to this GitHub issue. https://github.com/Microsoft/vscode/issues/3776

Can you make a comment there with exactly what you want to see? Also if you know the keybindings for Windows / Linux that would be helpful.
