### ISSUE TITLE
Breaks ⌘+K to clear Terminal

### ISSUE THREAD

**Issue by JamieMason** [Microsoft/vscode-sublime-keybindings#64]
When this plugin is enabled it is no longer possible to use ⌘+K to clear VS Code's Terminal.

Please let me know if there is any more information you need from me, thanks.

**Comment by Tyriar** [comment]
You may be able to fix this by redefining the cmd+k keybinding to clear the terminal. Also ctrl+k might not work also

**Comment by JamieMason** [comment]
Thanks @Tyriar, that worked. 

Here are the steps I followed:

1. Reinstall Sublime Text Keymap.
1. Reload.
1. Code -> Preferences -> Keyboard Shortcuts.
1. Search `clear`.
1. Edit `workbench.action.terminal.clear`.
1. Enter `⌘+K` and hit Enter.
1. Clearing terminal works again.

I will let you decide whether this needs closing or leaving open as needed :+1:

Thanks a lot.

**Comment by auchenberg** [comment]
@Tyriar We don't have any specific bindings  for CMD+K in https://github.com/Microsoft/vscode-sublime-keybindings, but we have a bunch of others who use CMD+K + <something>

Can I remap CMK+K in the mappings to take priority or is it a bug ?

**Comment by Tyriar** [comment]
@auchenberg overriding keybindings that have chord keybindings such as cmd+k and ctrl+k is a bit of a special case. For starters, chord keybindings don't work in the terminal because of this section of code:

https://github.com/Microsoft/vscode/blob/af6b8302fae66a2898ac8180c98221892d6c765f/src/vs/workbench/parts/terminal/electron-browser/terminalInstance.ts#L321-L328

This asks the keybinding service whether this keystroke will result in a command contained within the `terminal.integrated.commandsToSkipShell` whitelist. Because mutli-part keybindings like chord keybindings cannot be evaluated by this, all of them are ignored.

This problem led us to allow chord keybindings to be overridden when they contains a `when` clause, the only caveat is that said keybinding must be declared after all of the chord keybindings. This is because all keybindings have a priority, generally defined by when they are declared (non-extension keybindings can set this priority manually).

That's the reason I said *may* fix; it will only work if the cmd+k keybinding contributed by this extension is declared *after* the cmd+k chord keybindings. I'm not sure if the order from the contributions in the package.json is respected or not.

**Comment by aaemnnosttv** [comment]
Simply configuring Cmd + K to clear the terminal fixed it, and does not conflict with other sublime bindings from what I've seen likely because the context (When) is limited to the terminal focus.

The key binding does not actually change, since it was already Cmd + K, but it gets defined as a User binding rather than a default which seems to raise the priority of this binding thus resolving the conflict. 👍
